// ============================================
// CERTIFICATIONS DATA
// ============================================
export const CERTIFICATIONS = [
  {
    id: 'oracle-oci-ai',
    title: 'OCI 2025 — AI Foundations Associate',
    org: 'Oracle University',
    date: 'Aug 2025',
    categoryFr: 'Cloud & IA',
    categoryEn: 'Cloud & AI',
    pdf: '/certifications/oracle-oci-ai-foundations.pdf',
    verifyUrl: '',
  },
  {
    id: 'stanford-cip',
    title: "Code in Place — Certificate of Completion",
    org: 'Stanford University',
    date: '2026',
    categoryFr: 'Informatique',
    categoryEn: 'Computer Science',
    pdf: '/certifications/stanford-code-in-place.pdf',
    verifyUrl: 'https://codeinplace.stanford.edu/cip6/certificate/nh4cun',
  },
  {
    id: 'icsc-2026',
    title: 'ICSC 2026 — International Computer Science Competition',
    org: 'ICSC',
    date: 'Jul 2026',
    categoryFr: 'Compétition',
    categoryEn: 'Competition',
    pdf: '/certifications/icsc-2026-participation.pdf',
    verifyUrl: '',
  },
  {
    id: 'dclic-web-junior',
    title: 'D-CLIC — Développeur Web Junior',
    org: 'OIF / Formez-vous au numérique',
    date: 'Jul 2026',
    categoryFr: 'Développement Web',
    categoryEn: 'Web Development',
    pdf: '/certifications/dclic-developpeur-web-junior.pdf',
    verifyUrl: '',
  },
  {
    id: 'forcen-marketing',
    title: 'Certificat en Marketing Digital',
    org: 'FORCE-N',
    date: 'Jul 2026',
    categoryFr: 'Business',
    categoryEn: 'Business',
    pdf: '/certifications/forcen-marketing-digital.pdf',
    verifyUrl: '',
  },
  {
    id: 'forcen-entrepreneuriat',
    title: 'Certificat en Entrepreneuriat',
    org: 'FORCE-N',
    date: 'Jan 2026',
    categoryFr: 'Business',
    categoryEn: 'Business',
    pdf: '/certifications/forcen-entrepreneuriat.pdf',
    verifyUrl: '',
  },
  {
    id: 'saylor-cs105',
    title: 'CS105: Introduction to Python',
    org: 'Saylor Academy',
    date: 'Jan 2025',
    categoryFr: 'Programmation',
    categoryEn: 'Programming',
    pdf: '/certifications/saylor-cs105-intro-python.pdf',
    verifyUrl: '',
  },
  {
    id: 'saylor-cs101',
    title: 'CS101: Intro to Computer Science I',
    org: 'Saylor Academy',
    date: 'Jan 2025',
    categoryFr: 'Informatique',
    categoryEn: 'Computer Science',
    pdf: '/certifications/saylor-cs101-intro-cs.pdf',
    verifyUrl: '',
  },
  {
    id: 'saylor-esl003',
    title: 'ESL003: Upper-Intermediate English',
    org: 'Saylor Academy',
    date: 'Feb 2025',
    categoryFr: 'Langue',
    categoryEn: 'Language',
    pdf: '/certifications/saylor-esl003-english.pdf',
    verifyUrl: '',
  },
  {
    id: 'saylor-prdv200',
    title: 'PRDV200: Communicating with Data',
    org: 'Saylor Academy',
    date: 'Jul 2025',
    categoryFr: 'Data',
    categoryEn: 'Data',
    pdf: '/certifications/saylor-prdv200-data-communication.pdf',
    verifyUrl: '',
  },
  {
    id: 'ieee-membership',
    title: 'IEEE Student Membership',
    org: 'IEEE',
    date: '2024',
    categoryFr: 'Professionnel',
    categoryEn: 'Professional',
    pdf: '/certifications/ieee-student-membership.pdf',
    verifyUrl: '',
  },
  {
    id: 'opencv-bootcamp',
    title: 'OpenCV Bootcamp — Certificate of Excellence (98%)',
    org: 'OpenCV University',
    date: 'Apr 2026',
    categoryFr: 'Computer Vision',
    categoryEn: 'Computer Vision',
    pdf: '/certifications/opencv-university-bootcamp.pdf',
    verifyUrl: '',
  },
  {
    id: 'datacamp-python-fundamentals',
    title: 'Python Programming Fundamentals',
    org: 'DataCamp',
    date: 'Jun 2026',
    categoryFr: 'Data / Python',
    categoryEn: 'Data / Python',
    pdf: '/certifications/datacamp-python-programming-fundamentals.pdf',
    verifyUrl: '',
  },
  {
    id: 'datacamp-dsa-python',
    title: 'Data Structures and Algorithms in Python',
    org: 'DataCamp',
    date: 'May 2026',
    categoryFr: 'Data / Python',
    categoryEn: 'Data / Python',
    pdf: '/certifications/datacamp-data-structures-algorithms-python.pdf',
    verifyUrl: '',
  },
  {
    id: 'datacamp-intermediate-python',
    title: 'Intermediate Python for Developers',
    org: 'DataCamp',
    date: 'Jun 2026',
    categoryFr: 'Data / Python',
    categoryEn: 'Data / Python',
    pdf: '/certifications/datacamp-intermediate-python-for-developers.pdf',
    verifyUrl: '',
  },
  {
    id: 'datacamp-intro-python-dev',
    title: 'Introduction to Python for Developers',
    org: 'DataCamp',
    date: 'Jun 2026',
    categoryFr: 'Data / Python',
    categoryEn: 'Data / Python',
    pdf: '/certifications/datacamp-intro-python-for-developers.pdf',
    verifyUrl: '',
  },
  {
    id: 'datacamp-python-toolbox',
    title: 'Python Toolbox',
    org: 'DataCamp',
    date: 'Jun 2026',
    categoryFr: 'Data / Python',
    categoryEn: 'Data / Python',
    pdf: '/certifications/datacamp-python-toolbox.pdf',
    verifyUrl: '',
  },
  {
    id: 'datacamp-intro-data',
    title: 'Introduction to Data',
    org: 'DataCamp',
    date: 'May 2026',
    categoryFr: 'Data',
    categoryEn: 'Data',
    pdf: '/certifications/datacamp-introduction-to-data.pdf',
    verifyUrl: '',
  },
  {
    id: 'mimo-python',
    title: 'Python — Certificate of Achievement',
    org: 'Mimo',
    date: '2026',
    categoryFr: 'Programmation',
    categoryEn: 'Programming',
    pdf: '/certifications/mimo-python-achievement.pdf',
    verifyUrl: '',
  },
];

// Certifications mises en avant sur la home page (aperçu limité)
export const FEATURED_CERTIFICATION_IDS = ['oracle-oci-ai', 'stanford-cip', 'icsc-2026'];

export const getFeaturedCertifications = () =>
  FEATURED_CERTIFICATION_IDS.map((id) => CERTIFICATIONS.find((c) => c.id === id)).filter(Boolean);
